CREATE SCHEMA IF NOT EXISTS siren_db;
USE siren_db;

CREATE TABLE IF NOT EXISTS SESSION(
	session_id INT NOT NULL AUTO_INCREMENT,
    starttime DATETIME NOT NULL,
    endtime DATETIME NOT NULL,
	ip VARCHAR(15) NOT NULL,
    termsize VARCHAR(7) NOT NULL,
    client_id INT NOT NULL,
    PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS AUTH(
	auth_id INT NOT NULL AUTO_INCREMENT, 
	session_id INT NULL, 
	success TINYINT NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	passwd VARCHAR(100) NOT NULL, 
	timestmp DATETIME NOT NULL,
    PRIMARY KEY (auth_id),
    FOREIGN KEY (session_id) REFERENCES SESSION(session_id)
);

CREATE TABLE IF NOT EXISTS INPUT(
	input_id INT NOT NULL AUTO_INCREMENT,
    session_id INT NOT NULL,
    timestmp DATETIME NOT NULL,
    success TINYINT NOT NULL,
    input TEXT NOT NULL,
    PRIMARY KEY (input_id),
    FOREIGN KEY (session_id) REFERENCES SESSION(session_id)
);

CREATE TABLE IF NOT EXISTS TTPLOG(
	ttp_id INT NOT NULL AUTO_INCREMENT,
    session_id INT NOT NULL,
    ttylog MEDIUMBLOB NOT NULL,
    PRIMARY KEY(ttp_id),
    FOREIGN KEY (session_id) REFERENCES SESSION(session_id)
);

CREATE TABLE IF NOT EXISTS DOWNLOAD(
	download_id INT NOT NULL AUTO_INCREMENT,
    session_id INT NOT NULL,
    timestmp DATETIME NOT NULL,
    url TEXT NOT NULL,
    PRIMARY KEY (download_id),
    FOREIGN KEY (session_id) REFERENCES SESSION(session_id)
);